language: go
go:
- 1.6
script: go test -v ./... --cover
notifications:
  emails: false
  slack:
    secure: 1ydVSEiibr7xdP+x4MJRLu1gE2PmIT1L9iQX8YghtakxlIm4p0IJdwnePXgGcVnwMya95OqxAlmMV1lTyAx3059WRCUThSOTyDIYNPNL1tLWcdeLJdIh4EMTiF8bb8nhLOVxQK2c31bvDKFyHumQejM/QeMDvv+GIzwUsuRS6QalJsoH3+3rnebKfK3QYIRTz65OamtitDrDuT9crc0rhvTvWh8zFvRkmgYrHHHl7kPuVBXX72ERQ6X5wkE96egA4Bd9U38+wGdgFgy3bsDhLUGZnqBe8ococmI2Qqxn95GmSOzMNOcFnPQc5CQ/CXEUQZbLmwH1yk6zuzc1M04B/n9fou4gmsBF21UXn2e5fVsPASHXvvONHyfqNYQV4WRJpvqVpGY31Del0g3KUbb5JPjKGooGt2zcKwUJ8mGPg6mjHzxSmDPTOrdrBDBglJ/op2c0/tv1Uc1Wjy5oX2+jK5ePLHu0us1yhTMHATUvgTc/yZmJOpFVjQFKk7y6fi2037LedN+BN+At3ULSBJM9Z4DCuOgPm7I0qa0yUkEm8+GV6jtt+zVS9y+9HIijSZ7hjevcbe2YdVu6RnbQCohBgwCj9Eb4HzkPxIaHejyGhSnAwC+htsCXC+e+hg1WQ5dBjy4lm87nmr0XhzyjHDKJcwnbGWrLQWDlY9cdqvMHNis=
